name: kaagaz
description: Express thoughts with ease
publish_to: none

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: '>=0.13.0 <2.0.0'
  intl: '>=0.18.0 <0.20.0'
  logging: ^1.2.0
  handle: ^0.3.6
  go_router: ^14.2.0
  package_info_plus: ^8.0.0
  google_fonts: ^6.2.1
  flex_color_scheme: ^7.3.1
  path: ^1.9.0
  path_provider: ^2.1.3
  url_launcher: ^6.3.0
  flutter_svg: ^2.0.10+1
  sembast_web: ^2.4.0+2
  sembast: ^3.7.1+2
  collection: ^1.18.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  flutter_riverpod: ^2.5.1
  # TODO: remove after migration to sembast or some other library
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_gen_runner: ^5.5.0+1
  build_runner: ^2.4.11
  json_serializable: ^6.8.0
  freezed: ^2.5.2
  flutter_gen: ^5.5.0+1
  custom_lint: ^0.6.4
  riverpod_lint: ^2.3.10

flutter:
  uses-material-design: true
  generate: true
  deferred-components:
  # assets:
    #  - google_fonts/
    #  - assets/images/
    #  - assets/icons/

flutter_gen:
  output: lib/gen/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)
  # Optional
  integrations:
    flutter_svg: true

scripts:
  l10n: flutter gen-l10n
  dev: flutter run --dart-define-from-file=env/devel.json
